export interface AttendanceProps {
  props: Props
  page: string
  query: Query
  buildId: string
  isFallback: boolean
  customServer: boolean
  gip: boolean
  head: [string, Head][]
}

export interface Props {
  pageProps: PageProps
}

export interface PageProps {
  isServer: boolean
  store: unknown
  initialState: InitialState
  initialProps: InitialProps
}

export interface InitialState {
  apiStatus: ApiStatus
  translations: Translations
  lang: string
  version: string
  proxy: Proxy
  userContext: UserContext
  uberSearch: UberSearch
  memberList: unknown[]
  ministeringData: unknown
  ministeringStats: unknown
  ministeringAssignmentsReport: unknown
  memberCard: MemberCard
  householdCard: HouseholdCard
  ministeringFilter: MinisteringFilter
  unitPicker: UnitPicker
  ministeringAssignmentsFilter: MinisteringAssignmentsFilter
  ministeringPhotos: unknown
  newMemberReport: NewMemberReport
  birthdayList: BirthdayList
  sacramentAttendanceReport: SacramentAttendanceReport
}

export interface ApiStatus {
  showGenericError: boolean
  isPageError: boolean
  isFileNotFound: boolean
  isCaPage: boolean
}

export interface Translations {
  "letters.restoration.date": string
  "common.invalid.name": string
  "common.phone": string
  "ministering.attach.assignments": string
  "common.assistant.branch.clerk.membership": string
  "menu.meetinghouse.technology.training": string
  "common.assistant.ward.clerk": string
  "common.mission.executive.secretary.proselyting": string
  "common.expand.all": string
  "common.timeago.separator": string
  "menu.issue.limited-use.recommends": string
  "global.lang.de": string
  "letters.validation.field.required": string
  "common.same": string
  "letters.official.communication": string
  "menu.site.is.in.development": string
  "new-member.instructions": string
  "ministering.companionship": string
  "common.date.received": string
  "menu.relief.society": string
  "common.unbaptized": string
  "menu.district.primary": string
  "common.primary.presidency": string
  "leader-messaging.send-address-help": string
  "sacrament-attendance.year": string
  "leader-messaging.all-adult-members": string
  "common.table.filtered": string
  "menu.edit.contact.info": string
  "common.edit.and.summary": string
  "common.filtered.by": string
  "progress-record.view.all": string
  "leader-messaging.all-branch-presidents": string
  "common.default.stake.view.message": string
  "common.area": string
  "common.submit.to.district": string
  "letters.validation.select.restoration.date": string
  "common.age.label": string
  "leader-messaging.branch-leaders": string
  "ministering.q4": string
  "menu.custom.reports": string
  "ministering.ministers.self.assigned": string
  "ministering.q2": string
  "ministering.q3": string
  "common.reset": string
  "common.unexpected.error": string
  "menu.edit.quarterly.reports": string
  "ministering.q1": string
  "common.mailing.label.bold.name": string
  "menu.income.expense.detail": string
  "leader-messaging.district-council": string
  "ministering.past.week": string
  "common.m.short.label": string
  "common.timeago.years": string
  "ministering.ministering.assignments": string
  "common.young.women.presidency": string
  "menu.byu.pathway.worldwide": string
  "leader-messaging.calling": string
  "common.max.age.x": string
  "leader-messaging.all-elders-quorum-presidencies": string
  "ministering.rs.assignment.must.be.rs": string
  "move.ysa.mass.move": string
  "common.timeago.hours": string
  "menu.name.removal": string
  "common.clear.filters": string
  "common.bishop.x": string
  "common.f.short.label": string
  "htvt.household": string
  "common.male.short.label": string
  "leader-messaging.all-ward-mission-leaders": string
  "leader-messaging.members": string
  "common.show.phone": string
  "ministering.individuals.interviewed": string
  "common.quick.links": string
  "menu.ministering.assignment.proposals": string
  "new-member.responsibility": string
  "stats.households": string
  "global.lang.en": string
  "letters.unknown": string
  "common.assistant.stake.clerk.membership": string
  "menu.stake.sunday.school": string
  "menu.church.handbooks": string
  "birthday-list.birthday": string
  "ord.record.priesthood.ord": string
  "progress-record.parent.unit.message": string
  "months.august": string
  "progress-record.view.most.recent": string
  "menu.issue.limited.use.recommends": string
  "common.stake.executive.secretary": string
  "menu.sunday.school": string
  "common.priest.ordination": string
  "letters.validation.date.in.future": string
  "dashboard.general.handbook": string
  "letters.first.presidency": string
  "feedback.submit": string
  "500.server.error": string
  "common.add": string
  "ministering.interview.interval.instructions": string
  "letters.readmission.completed": string
  "common.here": string
  "menu.auxiliaries": string
  "menu.pef.endorsement.form": string
  "global.lang.fr": string
  "common.comma.space": string
  "letters.headquarter.communications.info": string
  "calendar.day.short.1": string
  "calendar.day.short.2": string
  "ministering.unassigned.households": string
  "calendar.day.short.3": string
  "menu.clerk.resources.lcr": string
  "feedback.loading.text": string
  "ministering.save.assignment.warning": string
  "menu.welcome.to.membership": string
  "common.suffix": string
  "common.membership.record.number": string
  "common.size": string
  "leader-messaging.young-single-adults": string
  "record.family": string
  "menu.donations": string
  "ministering.minister.not.authorized": string
  "global.lang.it": string
  "menu.create.member.of.record": string
  "ministering.interview.interval.instructions.no.link": string
  "menu.transfer.detail": string
  "common.priesthood.6.plural": string
  "common.all.members": string
  "common.warning": string
  "common.validation.member.not.found.title": string
  "common.faqs": string
  "common.district.presidency.counselors": string
  "common.select.all": string
  "common.left.arrows": string
  "menu.view.interviews": string
  "leader-messaging.all-executive-secretaries": string
  "progress-record.stakeview.default.message": string
  "calendar.day.short.4": string
  "calendar.day.short.5": string
  "menu.worldwide.leadership.training": string
  "calendar.day.short.6": string
  "calendar.day.short.7": string
  "htvt.assigned": string
  "common.mrn.label": string
  "letters.validation.select.confirmation.officiator": string
  "letters.ordination.date": string
  "leader-messaging.stake-general-priesthood-meeting": string
  "common.record": string
  "menu.print.mrs": string
  "common.mission.clerk": string
  "calendar.hour": string
  "record.female": string
  "member-lookup.view.member.profile": string
  "ministering.assignment": string
  "birthday-list.page.title": string
  "child-protection.certification.number.number": string
  "htvt.filter.subtitle.unassigned.all": string
  "ministering.no.duplicate.ministers": string
  "common.deny.remove": string
  "ministering.selected.assignments": string
  "menu.proposed.assignments": string
  "common.clerk.resources.communication": string
  "common.copyright.text": string
  "ministering.interview.current.quarter.info": string
  "leader-messaging.send-assignment": string
  "htvt.page.title": string
  "menu.membership.audit": string
  "ministering.assignment.proposals.info": string
  "leader-messaging.recipient-count-singular": string
  "menu.unit.settings": string
  "common.days": string
  "common.year": string
  "leader-messaging.all-bishops": string
  "common.view.selected.sections": string
  "birthday-list.young.men": string
  "common.ward.bishopric.counselors": string
  "menu.stake.young.women": string
  "global.lang.is": string
  "record.household.email": string
  "menu.record.patriarch.ordination": string
  "ord.temple.ordinances": string
  "menu.view.statistics": string
  "common.local.unit": string
  "menu.action.items": string
  "menu.temple": string
  "menu.actions.in.process": string
  "pef.submit.endorsement": string
  "ministering.edit.assignments": string
  "common.baptism.date": string
  "menu.finance": string
  "menu.payment.cards": string
  "ministering.no.companionships.created.previous.quarter": string
  "common.print.later": string
  "menu.stake.leadership": string
  "menu.place.or.remove.move.restriction": string
  "menu.welfare.service.requests": string
  "common.update": string
  "menu.limited.use.recommends": string
  "leader-messaging.all-auxiliary-presidencies": string
  "ministering.show.changes": string
  "common.previous": string
  "common.elder.ordination": string
  "common.unknown": string
  "common.branch_president.title": string
  "common.unit.name": string
  "letters.validation.confirmation.date.before": string
  "leader-messaging.all.melchizedek.priesthood": string
  "menu.print.certificates": string
  "menu.assisting.returning.from.war": string
  "common.member.name": string
  "pef.page.title": string
  "ministering.last.interview": string
  "common.priesthood.elder": string
  "menu.missionary.recommend.entry": string
  "letters.validation.explanation.to.long": string
  "common.record.number.heading": string
  "menu.rolls.and.lists": string
  "menu.temple.endowment": string
  "common.timeago.suffix.ago": string
  "common.little.delete": string
  "common.select.position": string
  "ministering.previous.quarter": string
  "menu.seminary.registration": string
  "common.priesthood.lowercase.5": string
  "months.january": string
  "common.unit": string
  "common.priesthood.lowercase.6": string
  "common.save": string
  "ministering.households": string
  "new-member.page.title": string
  "progress-record.eligible.aaronic": string
  "common.priesthood.lowercase.9": string
  "common.collapse.all": string
  "letters.restoration.of.blessings.interview.not.restore": string
  "menu.young.women": string
  "ministering.ministering.interviews": string
  "common.priesthood.lowercase.0": string
  "common.alert.father.not.found": string
  "leader-messaging.young-men": string
  "ministering.all.companionships": string
  "common.priesthood.lowercase.3": string
  "common.more.than.x.years": string
  "common.priesthood.lowercase.4": string
  "common.ward.missionary": string
  "sacrament-attendance.page.title": string
  "common.priesthood.lowercase.1": string
  "common.priesthood.lowercase.2": string
  "menu.members.without.callings": string
  "record.postal.code": string
  "common.select.member": string
  "common.branch.clerk": string
  "leader-messaging.elders": string
  "record.current.unit": string
  "recommend.void.recommend": string
  "common.select.year": string
  "ministering.current.quarter": string
  "leader-messaging.leaders": string
  "lost-members.member.not.found": string
  "letters.validation.select.confirmation": string
  "common.lookup": string
  "common.branch.missionary": string
  "common.all.individuals": string
  "record.household.phone": string
  "recommend.expired": string
  "months.11": string
  "months.10": string
  "menu.birthday.list": string
  "leader-messaging.error-no-sender-email": string
  "ministering.districts": string
  "menu.high.council": string
  "ministering.has.bishop.approved": string
  "ministering.assigned.households": string
  "menu.recommend.perform": string
  "ministering.no.companionships.created.previous.quarter.pre.ministering": string
  "menu.certificates": string
  "menu.budget.summary": string
  "menu.reports.rolls": string
  "menu.donation.batch.summary": string
  "member-lookup.find.individuals.and.pages": string
  "common.brothers": string
  "menu.boy.scouts": string
  "letters.cancellation.of.sealing.decision": string
  "common.select": string
  "common.saving.only": string
  "common.mission.executive.secretary": string
  "ministering.presidency.member.colon": string
  "common.district.clerk": string
  "common.send.message": string
  "child-protection.active": string
  "common.active.date": string
  "ministering.annotation.present.clerk": string
  "common.print.instructions": string
  "menu.request.add.remove.annotation": string
  "common.district.primary.presidency": string
  "common.unit.number": string
  "ministering.bishop.branch.president.approved.assignment": string
  "menu.child.protection.compliance.system": string
  "common.all": string
  "feedback.bug": string
  "common.home.phone": string
  "common.mailing.labels": string
  "callings.move.to": string
  "menu.all.reports": string
  "letters.validation.confirmation.officiator.priesthood": string
  "ministering.print.assignments": string
  "menu.issue.limited.use.group.recommends": string
  "common.unavailable": string
  "record.residential.address": string
  "menu.edit.membership.information": string
  "leader-messaging.ward-council": string
  "leader-messaging.allow-reply-all-help": string
  "menu.learn.about.ministering.description": string
  "menu.manage.companionships": string
  "common.please.contact.gsc": string
  "common.please.enter.member.name": string
  "common.age.colon": string
  "menu.law.of.the.fast.training": string
  "letters.confidential.communication": string
  "common.submit.to.stake": string
  "common.partial.date.help": string
  "ministering.individual.does.not.qualify": string
  "menu.create.a.report": string
  "menu.missionary.progress.record": string
  "ord.teacher.ordination.certificate": string
  "letters.type": string
  "beta.beta": string
  "common.display.options": string
  "common.membership.number": string
  "common.sisters": string
  "common.all.organizations": string
  "common.not.confirmed": string
  "common.loading.text": string
  "letters.instructions": string
  "common.print.multiple.copies": string
  "menu.record.aaronic.priesthood.ordination": string
  "common.young.men.presidency": string
  "global.proxy.message": string
  "common.no.results.report.table": string
  "ministering.attach.assignment": string
  "ord.child.blessing.certificate": string
  "menu.chastity.and.fidelity": string
  "letters.reinstatement.approval.instructions": string
  "common.invalid.date.expected.format": string
  "menu.ministering.sisters": string
  "menu.district.quarterly.report": string
  "common.selected.members": string
  "record.name": string
  "leader-messaging.from": string
  "ministering.assigned.current.quarter.info": string
  "recommend.temple.recommend.status.label": string
  "menu.district.presidency": string
  "progress-record.other.commitments": string
  "dashboard.welfare.resources": string
  "dashboard.data.privacy": string
  "ministering.no.companionships.in.district": string
  "leader-messaging.delivery-result-reject-notice-attachment-size-exceeded": string
  "menu.quarterly.report": string
  "common.continue": string
  "common.cmir.print.warning": string
  "menu.expense.detail": string
  "messages.menu.request.minutes": string
  "letters.readmission.interview.not.readmitted": string
  "ministering.new.and.modified.assignments": string
  "letters.confidential.record.communication": string
  "common.actions": string
  "ministering.quarterly.report.notify.clerk": string
  "leader-messaging.choose.file": string
  "ministering.past.month": string
  "letters.cancellation.of.sealing.approval.instructions": string
  "ministering.no.companion": string
  "ministering.recent.changes": string
  "calendar.month.long.8": string
  "ministering.teaser.description": string
  "calendar.month.long.9": string
  "birthday-list.relief.society": string
  "common.print.mailing.labels": string
  "calendar.month.long.4": string
  "calendar.month.long.5": string
  "calendar.month.long.6": string
  "global.error.global": string
  "employment.individuals.requesting": string
  "menu.current.assignments": string
  "calendar.month.long.7": string
  "ministering.interview.previous.quarter.info.qr": string
  "lost-members.cannot.find.member": string
  "leader-messaging.all-primary-presidencies": string
  "common.currently.serving.mission": string
  "common.current": string
  "child-protection.certification.status.page.title": string
  "lost-members.restore.to.unit": string
  "dashboard.order.office.supplies": string
  "lost-members.not.found.contact.family": string
  "months.july": string
  "ministering.hide.changes": string
  "common.back.to.reports": string
  "new-returning-member.title": string
  "global.lang.ty": string
  "404.use.browser.back.button": string
  "leader-messaging.church.purposes.only": string
  "letters.sealing.clearance.disapproval.instructions": string
  "menu.membership.records": string
  "common.show.current.unit": string
  "common.correct.errors": string
  "menu.recording.membership.info": string
  "common.months": string
  "common.save.and.continue": string
  "lost-members.not.found.bishop": string
  "leader-messaging.footer-text": string
  "common.all.priesthood.offices": string
  "lost-members.info.line2": string
  "lost-members.info.line1": string
  "menu.elders.quorum": string
  "common.little.undelete": string
  "common.branch.president": string
  "global.lang.sq": string
  "menu.serving.ysa": string
  "menu.sign.out": string
  "recommend.canceled": string
  "common.ward.clerk": string
  "common.summary": string
  "calendar.month.long.1": string
  "calendar.month.long.2": string
  "calendar.month.long.3": string
  "common.years": string
  "menu.employee.endorsement.system": string
  "common.priesthood.high_priest": string
  "menu.stake.young.men": string
  "ord.member.of.this.stake": string
  "ministering.show.individuals.info.rs": string
  "menu.clerk.resources": string
  "menu.release.notes": string
  "common.mtc.presidency.counselors": string
  "common.learn.more.rkats": string
  "menu.budget": string
  "record.confidential.description.view.annotation": string
  "lost-members.added.to.list": string
  "feedback.error.global": string
  "letters.reinstatement.disapproval.instructions": string
  "ministering.assignment.relief.society.info": string
  "common.priesthood.priest": string
  "common.build.date": string
  "common.view.in.cdol": string
  "birthday-list.high.priests.quorum": string
  "common.not.applicable": string
  "birthday-list.elders.quorum": string
  "common.default": string
  "feedback.thanks": string
  "htvt.not.assigned": string
  "common.save.as.draft": string
  "letters.lifting.of.sealing.restriction.disapproval.instructions": string
  "ministering.minister.already.assigned": string
  "common.stake": string
  "child-protection.status": string
  "common.total": string
  "common.missionary_training_center": string
  "menu.tithing.declaration": string
  "common.home.teaching.district.supervisor": string
  "menu.member.lookup": string
  "htvt.home.teachers": string
  "common.priesthood.office": string
  "common.street.address": string
  "common.household": string
  "ministering.district.name": string
  "sacrament-attendance.average": string
  "progress-record.missionary.service.error": string
  "common.please.correct.errors": string
  "record.head.of.household": string
  "leader-messaging.teaser.description.from.application": string
  "months.june": string
  "calendar.done": string
  "menu.record.bishop.ordination": string
  "menu.members.moved.out": string
  "common.confirmation.date": string
  "common.assistant.branch.clerk": string
  "common.delete": string
  "common.right.arrows": string
  "common.district.president": string
  "leader-messaging.file.too.big.error": string
  "common.show.current.age": string
  "letters.restoration.of.blessings.withdrawn.instructions": string
  "leader-messaging.all-branch-ysa-leaders": string
  "menu.readmission.after.name.removal": string
  "common.pending.record.information": string
  "common.print.certificate": string
  "common.stake.relief.society.presidency": string
  "ministering.hq.annotation.message": string
  "leader-messaging.all-young-men-leaders": string
  "common.melchizedek.priesthood.ordination": string
  "common.more.than.1.year": string
  "member-list.all.individuals": string
  "common.priesthood.label": string
  "global.lds.church": string
  "common.member.details": string
  "404.return.to.report.forms": string
  "common.edit": string
  "menu.member.focus": string
  "common.updating": string
  "common.date.colon": string
  "common.female.short.label": string
  "ministering.unassigned.ministering.brothers": string
  "common.relief.society.ministering.secretary": string
  "menu.resources": string
  "common.unexpected.error.title": string
  "menu.send.a.message": string
  "ministering.minister.not.old.enough": string
  "common.interview.date": string
  "leader-messaging.allow-reply-all": string
  "common.member.not.found": string
  "menu.membership.councils": string
  "common.saving": string
  "letters.first.presidency.decision.letter": string
  "common.m.long.label": string
  "common.individual.email": string
  "lost-members.join.headofhousehold": string
  "htvt.filter.subtitle.unassigned.home.teachers": string
  "common.elders.quorum.ministering.secretary": string
  "menu.young.church.service.missionaries": string
  "ministering.interview.previous.quarter.info": string
  "global.lang.zh": string
  "ord.primary.advancement.certificate": string
  "common.position": string
  "common.signature.parent.or.guardian": string
  "callings.set.apart": string
  "common.submit.to.hq": string
  "menu.new.leader.recommendations": string
  "menu.other": string
  "leader-messaging.branch-priesthood-leadership-meeting": string
  "common.relief.society.presidency": string
  "common.no.thanks": string
  "leader-messaging.clerks": string
  "menu.donation.batch.detail": string
  "ministering.search.members": string
  "menu.single.adults": string
  "child-protection.upload.new.certification": string
  "letters.validation.enter.explanation": string
  "letters.validation.ordination.date.before": string
  "child-protection.government.certifications.info": string
  "common.aging": string
  "leader-messaging.message-sent-error": string
  "leader-messaging.parents-young-women": string
  "common.stake.primary.presidency": string
  "menu.member.list": string
  "ministering.search.households": string
  "common.wards.and.branches": string
  "common.mission.presidency.counselors": string
  "record.prior.unit": string
  "leader-messaging.district-general-priesthood-meeting": string
  "ministering.assignment.proposals.publish.success": string
  "letters.reinstatement.withdrawn.instructions": string
  "common.removing": string
  "common.find.member.in.list": string
  "leader-messaging.search-recipients": string
  "common.success": string
  "menu.single.members": string
  "calendar.minute": string
  "feedback.love.it": string
  "birthday-list.months.to.show": string
  "letters.explanation": string
  "leader-messaging.ward-youth-council": string
  "record.birth.place": string
  "menu.priesthood": string
  "menu.primary": string
  "ministering.assignments": string
  "menu.supporting.correctional.facilities": string
  "common.mb": string
  "topics.0": string
  "common.deleting": string
  "letters.confirmation.officiator": string
  "common.email.label": string
  "ministering.rs.ministers.cannot.have.males": string
  "letters.validation.baptism.officiator.priesthood": string
  "record.city": string
  "ministering.assignment.not.authorized": string
  "menu.access.table": string
  "ministering.ministering.brothers": string
  "menu.senior.missionary.training": string
  "htvt.filter.subtitle.all.all": string
  "common.please.select": string
  "menu.create.reports": string
  "letters.validation.argument.out.of.range": string
  "sacrament-attendance.warn.over.100.percent": string
  "common.individual": string
  "common.month": string
  "ministering.assignment.attempt.annotation.unit.leader.subject": string
  "menu.mission.presidency": string
  "common.member.info": string
  "common.mrn.or.name.required": string
  "menu.stake.presidency": string
  "common.elders.quorum.presidency": string
  "common.correct.warnings": string
  "menu.new.member": string
  "leader-messaging.bishopric-youth-committee": string
  "menu.emplyment.resource.services": string
  "global.lang.nl": string
  "500.return.to.report.forms": string
  "htvt.filter.subtitle.assigned.visiting.teachers": string
  "common.kb": string
  "birthday-list.primary": string
  "menu.reports": string
  "common.print": string
  "common.validation.warning": string
  "common.date": string
  "common.error": string
  "ministering.ministering.label": string
  "pef.interview.questions": string
  "menu.ministering.relief.society": string
  "common.mtc.president": string
  "letters.reinstatement.completed": string
  "common.lose.changes.if.leave": string
  "menu.stake.primary": string
  "leader-messaging.sender-info-help": string
  "leader-messaging.no.file.chosen": string
  "menu.recommends": string
  "progress-record.view.details": string
  "child-protection.protecting.children.youth": string
  "common.setup": string
  "ministering.assignment.proposals.sisters": string
  "common.validation.officiator.name.not.match": string
  "class-and-quorum-attendance.overview.view.more": string
  "birthday-list.young.women": string
  "letters.first.presidency.decisions": string
  "feedback.do.you.have.feedback": string
  "ministering.youth.companion": string
  "menu.welfare.tools.caring": string
  "common.district.young.men.presidency": string
  "common.parent.unit.number": string
  "menu.donation.detail": string
  "common.mission": string
  "letters.confidential.document": string
  "ministering.delete.district": string
  "leader-messaging.all-sunday-school-presidencies": string
  "common.print.options": string
  "ministering.ministers.required": string
  "menu.confidential.information": string
  "menu.bishopric": string
  "months.september": string
  "menu.stake.family.history": string
  "lost-members.send.to.au.unit": string
  "menu.record.convert.baptism": string
  "404.return.actions.in.process": string
  "common.district": string
  "menu.welfare.assistance.provided": string
  "letters.lifting.of.sealing.restriction.approval.instructions": string
  "menu.recipient.transactions": string
  "leader-messaging.all-aaronic-adult-leaders": string
  "htvt.filter.subtitle.assigned.home.teachers": string
  "letters.validation.select.priesthood.officiator": string
  "common.assistant.district.clerk.membership": string
  "lost-members.move.to.unit": string
  "500.page.title": string
  "ministering.current.assignments": string
  "common.format.name": string
  "calendar.day.long.2": string
  "pef.endorsement.forms": string
  "calendar.day.long.3": string
  "ministering.companionships.interviewed.label": string
  "common.multiple.copies": string
  "calendar.day.long.1": string
  "calendar.day.long.6": string
  "lost-members.member.in.unit": string
  "calendar.day.long.7": string
  "letters.sealing.clearance.approval.instructions": string
  "calendar.day.long.4": string
  "calendar.day.long.5": string
  "feedback.enhancement": string
  "letters.baptism.date": string
  "common.name.or.address": string
  "pef.endorse.invalid.recommend.message": string
  "common.aux.presidency": string
  "common.unhide": string
  "common.goal": string
  "menu.enter.expenses": string
  "common.clear.selections": string
  "global.proxy.title": string
  "letters.confidential.communications": string
  "ord.baptism.certificate": string
  "ord.deacon.ordination.certificate": string
  "menu.record.mel.priesthood.ordination": string
  "common.unassigned": string
  "record.legal.name": string
  "leader-messaging.all-young-women-presidencies": string
  "recommend.issue.new.recommend.title": string
  "letters.who.performed.ordination": string
  "calendar.month.long.10": string
  "common.submit.to.mission": string
  "calendar.month.long.12": string
  "new-member.24.months": string
  "common.processing": string
  "calendar.month.long.11": string
  "letters.restoration.of.blessings.disapproval.instructions": string
  "menu.we.encourage.suggestions": string
  "menu.income.expense.summary": string
  "feedback.invalid.filetype": string
  "common.members": string
  "common.no": string
  "ministering.interviews": string
  "menu.contact.us": string
  "menu.action.interview.list": string
  "months.december": string
  "menu.unit.statistics": string
  "ministering.start.with.no.assignments": string
  "common.submitted.date": string
  "404.return.to.organizations.callings": string
  "feedback.no.thanks": string
  "leader-messaging.virus.attachment.error": string
  "child-protection.certification": string
  "menu.patriarch": string
  "menu.conduct.membership.audit": string
  "menu.home.visiting.teachers": string
  "leader-messaging.all-men": string
  "move.select.new.hoh": string
  "calendar.week.short": string
  "menu.youth.recommend.report": string
  "common.landscape": string
  "common.unit.info": string
  "common.show.email": string
  "child-protection.all.statuses": string
  "menu.district.young.men": string
  "child-protection.expired": string
  "ministering.assignment.proposals": string
  "leader-messaging.all-organization-presidencies": string
  "common.mailing.label.instructions.title": string
  "common.print.single.copy": string
  "common.mailing.label.uppercase.name": string
  "menu.declaration.summary": string
  "letters.validation.select.priesthood": string
  "ministering.past.year": string
  "callings.calling": string
  "leader-messaging.all-relief-society-presidencies": string
  "custom-reports.home.teaching.companion": string
  "ministering.all.relief.societies": string
  "child-protection.training.status": string
  "common.mailing.label.instructions": string
  "common.priesthood.apostle": string
  "common.cannot.submit.melchizedek.message": string
  "calendar.day.very.short.4": string
  "calendar.day.very.short.5": string
  "calendar.day.very.short.6": string
  "menu.class.and.quorum.attendance.overview": string
  "calendar.day.very.short.7": string
  "feedback.select.category": string
  "calendar.day.very.short.1": string
  "ministering.ministering.sisters": string
  "calendar.day.very.short.2": string
  "calendar.day.very.short.3": string
  "menu.district.sunday.school": string
  "ministering.apply.assignments": string
  "common.address": string
  "menu.vpn": string
  "common.date.initiated": string
  "menu.out.of.unit": string
  "menu.application.first.presidency": string
  "htvt.all.households": string
  "common.select.an.organization": string
  "menu.organizations": string
  "menu.other.tools": string
  "ministering.add.companionship": string
  "common.member.not.found.in.unit": string
  "menu.record.death": string
  "menu.merge.participants": string
  "menu.high.priests.group": string
  "dashboard.handbook.2": string
  "menu.edit.meeting.start.times": string
  "callings.sustained": string
  "letters.validation.select.baptism": string
  "dashboard.handbook.1": string
  "404.return.to.home": string
  "menu.ministering.brothers": string
  "common.percent.complete": string
  "menu.si.qr": string
  "record.select.state": string
  "menu.approve.expenses": string
  "feedback.comments.required": string
  "menu.member.list.new": string
  "child-protection.certifications.info": string
  "progress-record.missionary.progress.record": string
  "menu.temple.recommend.status": string
  "common.mrn.or.name.and.birthdate.required": string
  "menu.help": string
  "common.detail": string
  "beta.closed.details": string
  "leader-messaging.district-leaders": string
  "common.oou.member.note": string
  "common.given.names": string
  "common.signature.bishop.branch.pres": string
  "leader-messaging.clear-all": string
  "common.cancel": string
  "menu.record.keeping.status": string
  "common.non.member.note": string
  "menu.without.recommend": string
  "ministering.annotation.present.main.leader": string
  "menu.financial.statements": string
  "common.teacher.ordination": string
  "ministering.individuals.no.companion": string
  "leader-messaging.subject": string
  "common.signature": string
  "menu.payee.transactions": string
  "common.switch.calling": string
  "common.search.label": string
  "common.priesthood.prospective_elder": string
  "common.privacy.policy": string
  "menu.clerk.resources.short": string
  "common.member.not.found.please.select.member": string
  "common.branch.presidency.counselors": string
  "ministering.ministers.cannot.have.opposite.gender.unless.married": string
  "menu.branch.presidency": string
  "common.bytes": string
  "common.stake.clerk": string
  "common.no.limit": string
  "menu.orgs.and.callings": string
  "birthday-list.age.explanation": string
  "menu.four.generations": string
  "ministering.add.district": string
  "menu.year.end.statements": string
  "ministering.all.unassigned": string
  "common.name.with.placeholders": string
  "menu.purchase.materials": string
  "menu.clerk.training.lessons": string
  "menu.manage.districts": string
  "menu.district.leadership": string
  "leader-messaging.recipient-count-plural": string
  "menu.forms": string
  "menu.ward.leadership": string
  "menu.feedback.link": string
  "common.mailing.label.first.last": string
  "ministering.district.number": string
  "ord.priest.ordination.certificate": string
  "letters.in.process": string
  "ministering.presidency.member": string
  "common.timeago.month": string
  "ministering.view.households": string
  "common.no.members.found.verify.and.try.again": string
  "common.copyright": string
  "common.select.deselect.all": string
  "common.show.gender": string
  "common.males.and.females": string
  "common.mailing.label.household.name": string
  "menu.manage.categories": string
  "common.remove": string
  "menu.request.add.remove.ordinance-restriction": string
  "months.november": string
  "leader-messaging.priesthood-executive-committee": string
  "menu.lcr.home": string
  "progress-record.progress.record": string
  "common.high.councilor": string
  "menu.by.organization": string
  "common.drop.files.text": string
  "leader-messaging.delivery-result-reject-notice": string
  "ministering.total.companionships.interviewed": string
  "common.rights.and.use": string
  "menu.ordinance.record.forms": string
  "child-protection.expiring": string
  "menu.topics.for.coordinating.councils": string
  "common.formatted.name": string
  "menu.singles": string
  "common.name.formatter.instructions": string
  "menu.record.child.record.baptism": string
  "leader-messaging.security.block.error": string
  "common.save.name": string
  "common.priesthood.teacher": string
  "ministering.review.and.publish.assignments": string
  "404.use.navigation": string
  "ministering.start.adding.district": string
  "menu.key.indicators": string
  "class-and-quorum-attendance.overview.pagination.fraction.piece.text": string
  "menu.new.returning.member": string
  "common.stake.young.men.presidency": string
  "calendar.prev": string
  "common.baptized": string
  "common.timeago.hour": string
  "menu.ces": string
  "leader-messaging.search-recipients-by-unit-info-help": string
  "ministering.companionships.interviewed": string
  "pef.endorse.submission.success": string
  "menu.lds.tools.app": string
  "ministering.assignment.proposals.in.progress.info": string
  "common.birthdate.required": string
  "menu.learn.about.ministering": string
  "common.mrn.or.name.placeholder": string
  "menu.participants": string
  "common.priesthood.0": string
  "common.priesthood.1": string
  "ministering.all.districts": string
  "common.priesthood.2": string
  "ministering.delete.assignment.warning": string
  "htvt.filter.subtitle.all.home.teachers": string
  "lost-members.last.known.address": string
  "common.priesthood.3": string
  "calendar.am": string
  "common.priesthood.4": string
  "common.priesthood.5": string
  "progress-record.eligible.endowment": string
  "common.priesthood.6": string
  "common.priesthood.7": string
  "menu.print.mailing.labels": string
  "common.priesthood.8": string
  "common.priesthood.9": string
  "menu.payment.request": string
  "menu.district.council": string
  "common.mission.presidency.counselors.proselyting": string
  "common.hide.slash.show": string
  "child-protection.past.due": string
  "leader-messaging.select-all": string
  "common.missionary.sister": string
  "menu.family.history": string
  "child-protection.certification.expired": string
  "common.show.address": string
  "leader-messaging.message-sent-success": string
  "lost-members.not.found.contact.residence": string
  "ministering.minister.must.have.priesthood": string
  "common.resume": string
  "access.access.denied.mission.president": string
  "letters.validation.interview.date": string
  "leader-messaging.email-icon-help": string
  "menu.seminary.and.institute.attendance": string
  "letters.first.presidency.decision": string
  "child-protection.expiration": string
  "htvt.filter.subtitle.unassigned.visiting.teachers": string
  "common.search.placeholder": string
  "menu.ward.and.branch.leadership": string
  "menu.church.service.missionary.system": string
  "leader-messaging.parents-young-men": string
  "common.priesthood.seventy": string
  "letters.confidential.actions": string
  "404.page.title": string
  "calendar.month.short.9": string
  "calendar.month.short.8": string
  "calendar.month.short.7": string
  "menu.stake.quarterly.report": string
  "calendar.month.short.6": string
  "calendar.month.short.5": string
  "calendar.month.short.4": string
  "calendar.month.short.3": string
  "calendar.month.short.2": string
  "calendar.month.short.1": string
  "menu.request.minutes": string
  "leader-messaging.all-branch-presidencies": string
  "menu.mission.leadership": string
  "ministering.edit.districts": string
  "months.may": string
  "menu.ministering.elders": string
  "menu.donation.adjustment": string
  "common.show.age": string
  "common.show.birth.date": string
  "common.return.to.lcr": string
  "menu.manage.oou.members": string
  "common.show.only.label": string
  "leader-messaging.clear-recipients": string
  "common.choose.files.text": string
  "menu.confidential": string
  "record.relationship": string
  "leader-messaging.add.attachments": string
  "menu.expense.summary": string
  "menu.assign.budget": string
  "leader-messaging.error.individual.have.no.email": string
  "common.nonmembers": string
  "menu.interviews": string
  "leader-messaging.all-callings": string
  "common.missionary.elder": string
  "child-protection.add.certification": string
  "common.period": string
  "calendar.month.short.11": string
  "calendar.month.short.12": string
  "menu.temple.entry.system": string
  "common.mission.president.proselyting": string
  "menu.only.bishops.have.access": string
  "menu.merge.duplicate": string
  "child-protection.started": string
  "letters.lifting.of.formal.membership.restrictions.date": string
  "common.missionaries": string
  "calendar.month.short.10": string
  "letters.lifting.of.sealing.restriction.decision": string
  "common.go.back": string
  "child-protection.certification.name": string
  "ministering.no.duplicate.assignments": string
  "common.assistant.stake.clerk": string
  "ministering.no.companionships.created": string
  "child-protection.completed": string
  "menu.lufas": string
  "common.leader": string
  "ministering.pending.assignments": string
  "menu.request.records": string
  "letters.readmission.withdrawn.instructions": string
  "menu.confidential.member.information.report": string
  "common.class": string
  "menu.find.individual": string
  "leader-messaging.all-bishoprics": string
  "common.priesthood.4.plural": string
  "common.district_president.title": string
  "common.options": string
  "leader-messaging.single-adults": string
  "menu.district.relief.society": string
  "common.generic.foot.usage": string
  "menu.meetinghouse.technology.docs": string
  "ministering.selected.companionships": string
  "menu.other.callings": string
  "common.orientation": string
  "letters.baptism.officiator": string
  "letters.did.not.conduct.interview": string
  "menu.welfare.tools": string
  "ministering.start.over": string
  "leader-messaging.all-young-women-class-presidencies": string
  "menu.expenses": string
  "birthday-list.first.month.to.show": string
  "leader-messaging.all-ward-ysa-leaders": string
  "ministering.unassigned.sisters": string
  "ministering.publish.assignments": string
  "common.pending.record.title": string
  "common.upload.exceeds.mb": string
  "common.priesthood.deacon": string
  "menu.recommend.temple.workers": string
  "months.march": string
  "child-protection.search.table": string
  "recommend.active": string
  "letters.restoration.of.blessings.approval.instructions": string
  "common.back": string
  "months.april": string
  "menu.byu.hawaii": string
  "menu.priesthood.auxiliaries": string
  "progress-record.not.yet.given.calling": string
  "menu.msr": string
  "leader-messaging.attachments": string
  "leader-messaging.error-enter-message": string
  "leader-messaging.all-women": string
  "menu.branch.leadership": string
  "common.family.name": string
  "pef.endorsement.confirmation": string
  "ministering.assignment.attempt.annotation.unit.leader.body": string
  "common.branch.executive.secretary": string
  "common.non.member": string
  "common.birth.date": string
  "leader-messaging.all-branch-mission-leaders": string
  "letters.validation.select.baptism.officiator": string
  "common.record.number.or.birth.date": string
  "ord.who.performed.ordination": string
  "menu.member.list.individuals": string
  "leader-messaging.teaser.description": string
  "ministering.no.assignment": string
  "menu.record.visits": string
  "common.ward.executive.secretary": string
  "leader-messaging.district-pec": string
  "leader-messaging.all-clerks": string
  "common.cell.phone": string
  "leader-messaging.recipient-count-filtered": string
  "leader-messaging.ward-leaders": string
  "letters.cancellation.of.sealing.disapproval.instructions": string
  "ministering.show.individuals.label": string
  "feedback.thanks.detailed": string
  "ministering.start.with.current": string
  "htvt.visiting.teachers": string
  "menu.manage.assignments": string
  "menu.average.sacrament.meeting.attendance": string
  "common.timeago.minute": string
  "menu.delete.member.of.record": string
  "pef.pef.endorsement": string
  "menu.applications": string
  "htvt.all.organizations": string
  "lost-members.email.address": string
  "ministering.show.individuals.info.eq": string
  "ministering.companionships.not.interviewed": string
  "common.table.no.records": string
  "common.certificate.label": string
  "common.password": string
  "letters.doctype.108": string
  "feedback.screenshot": string
  "letters.doctype.102": string
  "menu.manage.callings": string
  "letters.first.presidency.type.20": string
  "menu.stake.relief.society": string
  "letters.first.presidency.type.22": string
  "letters.first.presidency.type.21": string
  "letters.first.presidency.type.26": string
  "common.portrait": string
  "letters.validation.select.ordination": string
  "child-protection.certification.number": string
  "record.birth.country": string
  "letters.first.presidency.type.27": string
  "menu.new.bishop.recommendation": string
  "common.branch": string
  "letters.first.presidency.type.29": string
  "menu.stake.conferences": string
  "common.stake.sunday.school.presidency": string
  "common.stake.president": string
  "menu.youth.website": string
  "menu.tithing.settlement": string
  "letters.success": string
  "months.february": string
  "letters.reinstatement.interview.not.restore": string
  "leader-messaging.stake-priesthood-leadership-meeting": string
  "menu.young.men": string
  "menu.switch.calling": string
  "common.hide": string
  "menu.meetinghouse.technology.policies": string
  "letters.readmission.disapproval.instructions": string
  "calendar.next": string
  "common.timeago.months": string
  "ministering.print.interviews": string
  "progress-record.eligible.melchizedek": string
  "common.filter.by": string
  "menu.authorize.expenses": string
  "letters.first.presidency.type.19": string
  "letters.first.presidency.type.18": string
  "access.access.denied.non.lcr.user": string
  "common.president.x": string
  "menu.ecclesiastical.endorsement": string
  "common.stake.presidency.counselors": string
  "ministering.annotation.present.others": string
  "letters.doctype.0": string
  "months.7": string
  "months.8": string
  "leader-messaging.search-recipients-by-calling-info-help": string
  "menu.confidential.actions.process": string
  "progress-record.not.yet.aaronic.priesthood": string
  "months.9": string
  "menu.records": string
  "letters.doctype.4": string
  "months.3": string
  "letters.doctype.3": string
  "months.4": string
  "common.male.long.label": string
  "letters.doctype.2": string
  "months.5": string
  "menu.forms.certificates": string
  "letters.doctype.1": string
  "months.6": string
  "letters.doctype.8": string
  "letters.doctype.7": string
  "months.0": string
  "letters.doctype.6": string
  "months.1": string
  "common.ward": string
  "menu.officers.sustained": string
  "letters.doctype.5": string
  "months.2": string
  "common.eligible": string
  "new-member.12.months": string
  "ministering.individuals.not.interviewed": string
  "menu.members.with.callings": string
  "menu.attendance.rolls": string
  "ministering.assignment.elders.info": string
  "common.timeago.minutes": string
  "leader-messaging.error-enter-subject": string
  "common.fax": string
  "ministering.past.day": string
  "letters.validation.select.outcome": string
  "lost-members.info.step4": string
  "common.assigned": string
  "class-and-quorum-attendance.details.back.button.title": string
  "lost-members.info.step2": string
  "lost-members.info.step3": string
  "menu.unit.messages.title": string
  "common.stake.second.counselor": string
  "lost-members.info.step1": string
  "menu.pending.record.title": string
  "404.return.to.membership": string
  "dashboard.beta.available": string
  "menu.byu": string
  "feedback.category": string
  "common.gender.label": string
  "ministering.all.elders.quorums": string
  "menu.not.endowed": string
  "child-protection.include.youth": string
  "child-protection.are.you.sure.delete": string
  "lost-members.view.member.information": string
  "record.individual.phone": string
  "letters.readmission.decision": string
  "common.stake.first.counselor": string
  "child-protection.expiration.date": string
  "menu.manage.photos": string
  "common.assistant.district.clerk": string
  "common.mtc.executive.secretary": string
  "common.sunday.school.presidency": string
  "common.mailing.label.last.first": string
  "common.not.accountable": string
  "global.access.denied": string
  "feedback.dev.team.feedback": string
  "ord.high.priest.ordination.certificate": string
  "menu.finding.lost.members": string
  "common.approve": string
  "common.death.date": string
  "menu.home": string
  "leader-messaging.all-branch-councils": string
  "ministering.oou.cannot.be.assigned": string
  "common.mission_president.title": string
  "common.canceling": string
  "common.validation.mrn.not.valid": string
  "feedback.importance": string
  "common.timeago.seconds": string
  "letters.sealing.clearance.withdrawn.instructions": string
  "lost-members.not.found.instructions": string
  "leader-messaging.send-assignments": string
  "leader-messaging.search-for-recipients": string
  "record.male": string
  "common.view": string
  "letters.confirmation.date": string
  "leader-messaging.high-council-meeting": string
  "common.move.date": string
  "recommend.lost.or.stolen": string
  "stats.individuals": string
  "leader-messaging.delivery-result-message-sent": string
  "common.baptism.confirmation": string
  "common.more.dot.dot.dot": string
  "child-protection.child.youth.protection": string
  "ministering.not.generally.assigned": string
  "leader-messaging.recipients": string
  "menu.stake.statistics": string
  "common.name.label": string
  "menu.general.help": string
  "menu.create.record": string
  "member-lookup.phone.label": string
  "common.search.table.placeholder": string
  "letters.lifting.of.formal.membership.restrictions.decision": string
  "child-protection.not.started": string
  "letters.validation.date.before.decision.date": string
  "ministering.unassigned.ministering.households": string
  "leader-messaging.all-members": string
  "menu.clerk.resources.page.title": string
  "record.select.country": string
  "common.branches": string
  "menu.lessons": string
  "500.user.browser.back.button": string
  "menu.edit.member.class.assignments": string
  "ministering.start.over.info": string
  "common.submit": string
  "menu.participant.details": string
  "menu.members.moved.in": string
  "common.today": string
  "letters.restoration.of.blessings.completed": string
  "leader-messaging.error-select-recipients": string
  "menu.hastening.the.work": string
  "menu.ordinances": string
  "common.stake_president.title": string
  "common.select.month": string
  "common.submitting": string
  "common.high.priests.group.leadership": string
  "move.address.incomplete": string
  "menu.progress.record": string
  "ministering.interview.past.year.info": string
  "common.timeago.day": string
  "ord.member.of.other.stake": string
  "calendar.pm": string
  "ministering.assignment.proposals.brothers": string
  "record.father": string
  "leader-messaging.invalid-email-address-popup": string
  "letters.who.performed.confirmation": string
  "menu.district.family.history": string
  "child-protection.certification.number.optional": string
  "letters.cancellation.of.sealing.withdrawn.instructions": string
  "common.resubmit": string
  "menu.menu": string
  "common.assistant.ward.clerk.membership": string
  "common.melchizedek": string
  "common.timeago.year": string
  "common.close": string
  "pef.endorse.submission.failure": string
  "child-protection.sustained": string
  "menu.family.history.activity.report": string
  "common.single.copy": string
  "letters.doctype.23": string
  "letters.doctype.24": string
  "beta.exit.beta": string
  "menu.adjust.expenses": string
  "menu.boundary.leadership.change": string
  "common.stewardship.info": string
  "ministering.presidency.member.tooltip.eq": string
  "common.status.label": string
  "menu.other.reports": string
  "common.print.form": string
  "common.this.ward.or.branch": string
  "common.district.relief.society.presidency": string
  "menu.beta.overview": string
  "menu.seminary.and.institute.enrollment": string
  "lost-members.not.found.contact.member": string
  "letters.restoration.of.blessings.decision": string
  "menu.record.member.of.record.baptism": string
  "menu.district.young.women": string
  "member-lookup.email.label": string
  "menu.district.and.branch.leadership": string
  "letters.validation.ordination.officiator.priesthood": string
  "common.yes": string
  "ministering.unassigned.ministering.sisters": string
  "ministering.assigned.sisters": string
  "letters.doctype.12": string
  "common.confirm.delete": string
  "feedback.clerk.resources.communication": string
  "menu.lds.business.college": string
  "record.street1": string
  "leader-messaging.high-priests": string
  "record.street2": string
  "progress-record.error.friends.mutation": string
  "common.select.member.from.unit": string
  "menu.new.and.returning.member": string
  "common.aaronic": string
  "common.characters.left": string
  "common.sort.by": string
  "common.parent.name": string
  "common.work.phone": string
  "leader-messaging.stake-council": string
  "ministering.all.assignments": string
  "menu.member.unit.stats": string
  "class-and-quorum-attendance.overview.title": string
  "menu.byu.idaho": string
  "common.saved": string
  "common.district.aux.presidency": string
  "common.district.young.women.presidency": string
  "menu.ministering.resources": string
  "menu.officers.sustained.form": string
  "common.contact": string
  "common.gender.colon": string
  "menu.home.and.visiting.teaching": string
  "common.member": string
  "letters.lifting.of.sealing.withdrawn.disapproval.instructions": string
  "leader-messaging.stake-leaders": string
  "member-lookup.current.unit": string
  "menu.callings": string
  "ministering.split.filter.warning": string
  "feedback.feedback": string
  "menu.ministering": string
  "leader-messaging.message": string
  "leader-messaging.all-high-priests-group-leaderships": string
  "menu.boundary.proposals": string
  "menu.view.member.profiles": string
  "menu.beta.email": string
  "ministering.presidency.member.tooltip.rs": string
  "common.done": string
  "common.father.not.found": string
  "menu.record.child.blessing": string
  "common.more.details.dot.dot.dot": string
  "common.name.formatter": string
  "common.district.sunday.school.presidency": string
  "common.high.priest.ordination": string
  "ministering.eq.assignment.must.be.hoh": string
  "common.female.long.label": string
  "letters.password.protected": string
  "common.hide.dot.dot.dot": string
  "common.timeago.days": string
  "common.district.executive.secretary": string
  "progress-record.not.yet.received.ministering.assignment": string
  "leader-messaging.delivery-result-subject": string
  "leader-messaging.sending": string
  "menu.young.single.adults": string
  "common.stake.aux.presidency": string
  "common.initiated.by": string
  "common.confirmed": string
  "ministering.companionships": string
  "menu.member.list.households": string
  "common.deacon.ordination": string
  "common.do.you.want.to.continue": string
  "common.contact.us": string
  "ministering.currently.no.proposed.assignments": string
  "letters.interview.date": string
  "feedback.usability.issue": string
  "menu.membership": string
  "calendar.today": string
  "ministering.assigned.current.quarter.with.pending.info": string
  "common.notes": string
  "menu.cdol": string
  "ministering.delete.district.warning": string
  "common.signature.bishopric.or.branch.presidency": string
  "common.different.ward.or.branch": string
  "common.priesthood.office.label": string
  "letters.doctype.53": string
  "letters.read.letter.communicated.member": string
  "letters.who.performed.baptism": string
  "common.birthdate.label": string
  "htvt.filter.subtitle.assigned.all": string
  "letters.doctype.56": string
  "common.dismiss": string
  "common.wards.branches": string
  "common.bishop": string
  "months.october": string
  "self-reliance.member.self.reliance": string
  "common.showing.x.results": string
  "class-and-quorum-attendance.overview.filter.by.quorum.class.option.all.classes": string
  "letters.readmission.approval.instructions": string
  "self-reliance.stake.self.reliance": string
  "letters.validation.response.already.posted": string
  "ministering.already.has.ministers": string
  "menu.leader.resources": string
  "common.mailing.label.individual.name": string
  "menu.lds.mail": string
  "leader-messaging.all-young-women-leaders": string
  "common.day": string
  "ministering.assigned.to.each.other": string
  "common.stake.young.women.presidency": string
  "htvt.filter.subtitle.all.visiting.teachers": string
  "common.i.understand": string
  "common.bishop.title": string
  "feedback.translation": string
  "common.record.with.warnings": string
  "leader-messaging.young-women": string
  "menu.donation.reports": string
  "menu.missionary": string
  "menu.adult.member.self.reliance": string
  "leader-messaging.parents-primary-children": string
  "common.list.label": string
  "leader-messaging.send-message": string
  "common.mailing.label.head.of.house.name": string
  "letters.expiration.date": string
  "letters.priesthood.officiator": string
  "menu.overview": string
  "ministering.show.photos": string
  "common.show": string
  "common.f.long.label": string
  "leader-messaging.all-ward-councils": string
  "ministering.assignment.proposals.apply.info": string
  "common.wards": string
  "new-member.show.for.past": string
  "leader-messaging.message-sent-confirmation-email": string
  "common.delete.message": string
  "common.more.actions": string
  "letters.validation.select.lifting.of.formal.membership.restrictions.date": string
  "menu.edit.member.calling": string
  "common.mission.president.companion": string
  "menu.patriarchal.blessing.submission": string
  "feedback.clerk.resources": string
  "common.action": string
  "menu.fsy": string
  "letters.sealing.clearance.decision": string
  "menu.only.bishops.have.access.training": string
  "menu.move.out": string
  "class-and-quorum-attendance.overview.pagination.items.per.page.title": string
  "leader-messaging.search-recipients-info-help": string
  "child-protection.government.certifications": string
  "pef.endorse.member": string
  "ord.elder.ordination.certificate": string
  "common.min.age.x": string
  "common.all.sections": string
  "common.full.name": string
  "common.timeago.prefix.ago": string
  "menu.edit.unit.abbreviations": string
  "menu.welcome.to.orgs.and.callings": string
  "menu.new.stake.counselor.recommendation": string
  "ministering.proposed.assignments": string
  "common.username": string
  "leader-messaging.add-recipients": string
  "menu.allocation.percent": string
  "recommend.cancel.recommend": string
  "common.phone.number.label": string
  "common.mailing.label.other.options": string
  "leader-messaging.branch-council": string
  "child-protection.page.title": string
  "menu.transfer.summary": string
  "menu.transfers": string
  "common.table.count": string
  "menu.beta.administration": string
  "letters.unread": string
  "leader-messaging.all-young-men-presidencies": string
  "common.unordained": string
  "menu.welfare.help.line": string
  "menu.ocl": string
  "menu.boundary.realignment": string
  "common.mission.president.ecclesiastical": string
}

export interface Proxy {
  proxyOptions: unknown[]
  proxySearchResults: unknown[]
  loading: boolean
}

export interface UserContext {
  environment: string
  version: string
  contextPath: string
  unit: Unit
  isLcrClassCallingHtvtEnabled: boolean
  subOrgs: SubOrg[]
  unitOrgs: UnitOrg[]
  fullDateFormatJs: string
  fullDateFormatOmitYearJs: string
  emptyNameGroup: EmptyNameGroup
  ldsAccountUsername: string
  ldsAccountPreferredName: string
  individualId: number
  roles: string[]
  activePosition: number
  activePositionUnitNumber: number
  activePositionEnglish: string
  positions: Position[]
  proxied: boolean
  betaEnv: boolean
  betaTerms: boolean
  nonBetaUrl: string
  betaUrl: string
  addressUrl: string
  cdolUrl: string
  cdolUnitUrl: string
  luHelpUrl: string
  changeBoundaryUrl: string
  changeBoundaryStakeUrl: string
  viewBoundaryProposalStatusUrl: string
  stakeConferencesUrl: string
  surveyUrl: string
  newBishopUrl: string
  newBishopStatusUrl: string
  newStakeCounselorUrl: string
  newPatriarchUrl: string
  recommendMissionPresidentUrl: string
  welfareServicesUrl: string
  cqaBulkWait: string
  teasers: Teasers
  menus: Menu[]
  reactDomain: unknown
  appUpdatedFormattedDate: string
}

export interface Unit {
  unitName: string
  unitNumber: number
  type: string
  translatedType: string
  children: unknown
  parentUnitName: string
  parentUnitNumber: number
  parentType: string
  grandparentType: string
  missionName: string
  missionUnitNumber: number
  areaName: string
  areaUnitNumber: number
  msrOfficeName: string
  msrOfficeUnitNumber: number
}

export interface SubOrg {
  unitNumber: number
  subOrgId: number
  orgTypeIds: number[]
  defaultOrgTypeIds: number[]
  name: string
  children: Children[]
  userCanEditCallings: boolean
  isClass: boolean
  isRealClass: boolean
  isSplit: boolean
  classGroup?: string
  firstTypeId: number
  isCombined: boolean
  parentName: unknown
  gender?: string
}

export interface Children {
  unitNumber: number
  subOrgId: number
  orgTypeIds: number[]
  defaultOrgTypeIds: number[]
  name: string
  children: Children2[]
  userCanEditCallings: boolean
  isClass: boolean
  isRealClass: boolean
  isSplit: boolean
  classGroup?: string
  firstTypeId: number
  isCombined: boolean
  parentName: string
  gender?: string
}

export interface Children2 {
  unitNumber: number
  subOrgId: number
  orgTypeIds: number[]
  defaultOrgTypeIds: number[]
  name: string
  children: unknown[]
  userCanEditCallings: boolean
  isClass: boolean
  isRealClass: boolean
  isSplit: boolean
  classGroup: unknown
  firstTypeId: number
  isCombined: boolean
  parentName: string
  gender: unknown
}

export interface UnitOrg {
  children?: Children3[]
  unitOrgUuid: string
  unitUuid: string
  unitNumber: number
  unitOrgName: string
  unitOrgTypeIds: number[]
  isClass: boolean
}

export interface Children3 {
  children?: Children4[]
  unitOrgUuid: string
  unitUuid: string
  unitNumber: number
  unitOrgName: string
  unitOrgTypeIds: number[]
  isClass: boolean
}

export interface Children4 {
  children: unknown
  unitOrgUuid: string
  unitUuid: string
  unitNumber: number
  unitOrgName: string
  unitOrgTypeIds: number[]
  isClass: boolean
}

export interface EmptyNameGroup {
  formattedLocal: unknown
  formattedLatin: unknown
  name1: Name1
  name2: unknown
  name3: unknown
  autoRomanize: boolean
}

export interface Name1 {
  family: unknown
  given: unknown
  suffix: unknown
  translitSource: boolean
  writingSystem: string
  label: string
  labelKey: string
}

export interface Position {
  positionTypeId: number
  positionName: string
  unitNumber: number
}

export interface Teasers {
  smallTeasers: unknown[]
  mediumTeasers: MediumTeaser[][]
}

export interface MediumTeaser {
  id: string
  feature: unknown
  url?: string
  urlInNewWindow: boolean
  imageUrl: string
  title: string
  description: string
}

export interface Menu {
  type?: string
  hiddenMenuSearchOnly: boolean
  name: string
  liClass: unknown
  ulClass?: string
  subMenuId?: string
  allowEmptyMenu: boolean
  sorted: boolean
  includeRoles?: string[][]
  excludeRoles: unknown
  item?: Item
  items?: Item2[]
  columns?: Column[][]
  parentSubOrgType?: string
  parentSubOrgId?: number
}

export interface Item {
  hiddenMenuSearchOnly: boolean
  name: unknown
  menuSearchName: unknown
  title: unknown
  parentTitle: unknown
  url: string
  urlInNewWindow: boolean
  uiSref: unknown
  uiSrefOpts: unknown
  liClass?: string
  includeRoles: unknown
  excludeRoles: unknown
  react: boolean
  subOrgId: unknown
}

export interface Item2 {
  hiddenMenuSearchOnly: boolean
  name: string
  menuSearchName: unknown
  title: unknown
  parentTitle: string
  url: string
  urlInNewWindow: boolean
  uiSref: unknown
  uiSrefOpts: unknown
  liClass: unknown
  includeRoles: unknown
  excludeRoles: unknown
  react: boolean
  subOrgId: number
}

export interface Column {
  type?: string
  hiddenMenuSearchOnly?: boolean
  name: string
  liClass?: string
  ulClass?: string
  subMenuId: unknown
  allowEmptyMenu?: boolean
  sorted?: boolean
  includeRoles?: string[][]
  excludeRoles: unknown
  item: unknown
  items: Item3[]
  columns: unknown
  parentSubOrgType: unknown
  parentSubOrgId: unknown
}

export interface Item3 {
  hiddenMenuSearchOnly: boolean
  name: string
  menuSearchName?: string
  title: unknown
  parentTitle?: string
  url: string
  urlInNewWindow: boolean
  uiSref?: string
  uiSrefOpts?: string
  liClass?: string
  includeRoles?: string[][]
  excludeRoles?: string[][]
  react: boolean
  subOrgId?: number
}

export interface UberSearch {
  memberResults: unknown[]
  pageResults: unknown[]
  loading: boolean
}


export interface MemberCard {
  loading: boolean
  error: unknown
  memberCardList: unknown
}

export interface HouseholdCard {
  loading: boolean
  error: unknown
  householdCardList: unknown
}

export interface MinisteringFilter {
  searchText: string
  selectedDistricts: unknown
  selectedOptionFilters: unknown
  selectedOrg: string
  selectedQuarter: string
  unassignedSearchText: string
  showNotGenerallyAssigned: boolean
}


export interface UnitPicker {
  selectedUnit: unknown
  searchValue: unknown
}

export interface MinisteringAssignmentsFilter {
  householdsSearchText: string
  householdsAssignedValue: string
  householdsOrganizationsValue: string
  individualsSearchText: string
  individualsOrgFilter: string
  individualsMissingFilter: string
}

export interface NewMemberReport {
  data: unknown[]
  searchText: string
  term: string
  showAge: boolean
  isLoading: boolean
}

export interface BirthdayList {
  data: unknown[]
  monthsShown: string
  unitOrg: string
  month: number
  showAge: boolean
  isLoading: boolean
}

export interface SacramentAttendanceReport {
  data: unknown[]
  years: unknown[]
  year: unknown
  editMonth: unknown
  isSaving: boolean
  isLoading: boolean
  isInitialLoad: boolean
  tempWeeks: unknown[]
}

export interface InitialProps {
  attendees: Attendee[]
  dates: Date2[]
  hasPermissionToEdit: boolean
  isDisplayableUnit: boolean
  individualId: number
  isShowUnitPicker: boolean
  lang: string
  limitUnitOrgUuid: unknown
  userContextUnitOrgs: UserContextUnitOrgs
  rootUnitOrgNodes: RootUnitOrgNode[]
  selectedUnitNumber: number
}

export interface Attendee {
  cmisId: number
  entries: Entry[]
  gender: string
  sortName: string
  displayName: string
  unitOrgsCombined: string[]
  uuid: string
}

export interface Entry {
  date: Date
  isMarkedAttended: boolean
}

export interface Date {
  localeMonthDay: string
  isoYearMonthDay: string
  epochSeconds: number
}

export interface Date2 {
  localeMonthDay: string
  isoYearMonthDay: string
  epochSeconds: number
}

export interface UserContextUnitOrgs {
  orgTypes: unknown
  parentUnitOrg: unknown
  uuid: string
  name: unknown
}

export interface RootUnitOrgNode {
  children: Children5[]
  unitOrgUuid: string
  unitUuid: string
  unitNumber: number
  unitOrgName: string
  unitOrgTypeIds: number[]
  isClass: boolean
}

export interface Children5 {
  children?: Children6[]
  unitOrgUuid: string
  unitUuid: string
  unitNumber: number
  unitOrgName: string
  unitOrgTypeIds: number[]
  isClass: boolean
}

export interface Children6 {
  children: unknown
  unitOrgUuid: string
  unitUuid: string
  unitNumber: number
  unitOrgName: string
  unitOrgTypeIds: number[]
  isClass: boolean
}

export interface Query {
  lang: string
}

export interface Head {
  charSet?: string
  name?: string
  content?: string
}
