export interface Calling {
  mrn: string
  unitNumber: number
  unitName?: string
  subOrgTypeId?: number
  subOrgId?: number
  customSubOrgName: any
  parentSubOrgId?: number
  positionTypeId?: number
  positionId?: number
  standardPosition: boolean
  position: string
  displaySequence?: number
  activeCalender?: string
  activeDate: string
  setApartCalender?: string
  setApartDate?: string
  leaderHomePhone?: string
  leaderWorkPhone: any
  id: number
  memberUnitNumber: number
  memberUnitName: string
  name: string
  nameOrder: number
  birthDate: string
  birthDateSort: string
  birthdDateDisplay: string
  phone?: string
  age: number
  outOfUnit: boolean
  stake: boolean
  district: boolean
  organization: string
  spokenName: string
  gender: string
  priesthood?: string
  email?: string
  errors: unknown
  subOrgType?: string
  custom: boolean
  sustainedDate: string
  setApart: boolean
}
